config/routes.rb
Rails.application.routes.draw do

  resources :users 
  resources :posts do
  resource :comments
  end
  root 'posts#index'
        get '/signup' => 'users#new'
        post '/users' => 'users#create'
        get '/login' => 'session#new'
        post '/login' => 'session#create'
        get '/logout' => 'session#destroy'
        get  '/posts/:post_id/comments/:id/edit'=>'comments#edit',as: :edit_post_comment
        patch  '/posts/:post_id/comments/:id/edit'=>'comments#update',as: :update_post_comment
        delete  '/posts/:post_id/comment/:id/delete'=> 'comments#destroy',as: :delete_post_comment
        
        get '/posts/:post_id/comment/:id/like' =>'comments#like',as: :post_comment_like
        get '/posts/:post_id/comment/:id/dislike' =>'comments#dislike',as: :post_comment_dislike

        get '/posts/:post_id/like' =>'posts#like',as: :post_like
        get '/posts/:post_id/dislike' =>'posts#dislike',as: :post_dislike
                  
               

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  	 has_many :likes, as: :likeble

  	 
  	 def already_likes?(comment)
  self.likes.find(:all, :conditions => ['comment_id = ?', comment.id]).size > 0
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :b_action,only:[:new,:show ,:edit,:update,:destroy ,:create]
  before_action :authorize ,except:[:show]
  def new
  
    @comments = @post.comments.all
    @comment = @post.comments.new
  end

  def show
  end

  def create   
       @comment = @post.comments.create(find_params)
  	   @comment.user_id = current_user.id

  	   if @comment.save! 
  	   	   redirect_to new_post_comments_path(@post)
  	   else
  	   		render 'new'
  	   end
  end

  def edit
      @comments = @post.comments.all
      @comment = Comment.find(params[:id])


  end
  def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
   		redirect_to  new_post_comments_path(@post)
  end

  def update
        @comment = Comment.find(params[:id])
        @comment.update(find_params)
        redirect_to new_post_comments_path(@post)
  end

  def like
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])

        if current_user.already_dislikes?(@comment,'Comment')
           like = current_user.likes.where(likeble_id: @comment.id ,
           user_id: current_user.id ,likeble_type: 'Comment').first
           like.like_status = true
           like.save
           redirect_to  new_post_comments_path(@post)

         else
           if current_user.already_likes?(@comment ,'Comment')
              redirect_to  new_post_comments_path(@post)
           else
              like = @comment.likes.create()
              like.user_id = current_user.id
              like.like_status = true
              like.save
              redirect_to  new_post_comments_path(@post) 
            end
        end
  end
  def dislike
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])


        if current_user.already_likes?(@comment,'Comment')
           like = current_user.likes.where(likeble_id: @comment.id ,
           user_id: current_user.id,likeble_type: 'Comment').first
           like.like_status = false
           like.save
           redirect_to  new_post_comments_path(@post)

        else
          if current_user.already_dislikes?(@comment ,'Comment')
             redirect_to  new_post_comments_path(@post)
          else
             like = @comment.likes.create()
             like.user_id = current_user.id
             like.like_status = false
             like.save
             redirect_to  new_post_comments_path(@post) 
          end
       end
  end

  private 
 def b_action
    @post = Post.find(params[:post_id])

 end
 def find_params
    params.require(:comment).permit(:desc,:user_id ,:post_id)
 end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%@post = Post.find(params[:post_id]) %>
Posted by <%= User.find(@post.user_id).f_name + User.find(@post.user_id).l_name %> <br>
<div><h3><%= @post.title %></h3>
 <%= @post.body %> <br>
 
    <%=link_to  'Like' %> 
    &nbsp; &nbsp;<%= @post.likes.count %>
    <%#if current_user.already_likes?(@post)%>
     <%#else%>
     <%#end%>
 <b>Comment &nbsp; &nbsp;   <%= @post.comments.count %></b> 
 </div>
<br><br>


Comments :
<% @comments.each do |comnt|%>
<%@user = User.find(comnt.user_id) %>
<div>
<h5><%= @user.f_name%>
<%= @user.l_name%></h5>

<%= comnt.desc %>
<br>
<%=link_to  'Like' ,post_comment_like_path(@post ,comnt) %>
  &nbsp; &nbsp;<%= comnt.likes.where(like_status: true).count %>

<%=link_to  'UnLike',post_comment_dislike_path(@post ,comnt) %>
  &nbsp; &nbsp;<%= comnt.likes.where(like_status:false).count %>

<%if (current_user.id == comnt.user_id)%>
<%= link_to 'Edit' , edit_post_comment_path(@post ,comnt) %>
<%= link_to  'Delete Post' , delete_post_comment_path(@post,comnt)  ,method: :delete,:notice=> 'Successfully deleted'%>
<%else%>
<%end%>
</div>
<%end%>

app/views/comments/edit.html.erb
<%= render 'comment'%>

<pre>
<%=current_user.f_name%><%= current_user.l_name%>
<%= form_for :comment, :url=> update_post_comment_path(@post ,@comment), method: :patch do |f|%>
  <%= f.text_area :desc %><br>
  <%= f.submit "Submit" %>
  <%end%> 

</pre>
<%= link_to 'Home' , root_path%>

app/views/comments/new.html.erb
<%= render 'comment'%>

<pre>
<%=current_user.f_name%><%= current_user.l_name%>
<%= form_for :comment, :url=> post_comments_path(@post) do |f|%>
  <%= f.text_area :desc %><br>
  <%= f.submit "Submit" %>
  <%end%> 

</pre>
<%= link_to 'Home' , root_path%>