config/routes.rb
Rails.application.routes.draw do

  resources :users 
  resources :posts do
  resource :comments
  end
  root 'posts#index'
        get '/signup' => 'users#new'
        post '/users' => 'users#create'
        get '/login' => 'session#new'
        post '/login' => 'session#create'
        get '/logout' => 'session#destroy'
        get  '/posts/:post_id/comments/:id/edit'=>'comments#edit',as: :edit_post_comment
        patch  '/posts/:post_id/comments/:id/edit'=>'comments#update',as: :update_post_comment
        delete  '/posts/:post_id/comment/:id/delete'=> 'comments#destroy',as: :delete_post_comment
        
        get '/posts/:post_id/comment/:id/like' =>'comments#like',as: :post_comment_like
        get '/posts/:post_id/comment/:id/dislike' =>'comments#dislike',as: :post_comment_dislike

        get '/posts/:post_id/like' =>'posts#like',as: :post_like
        get '/posts/:post_id/dislike' =>'posts#dislike',as: :post_dislike
                  
               

end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password
has_many :posts
has_many :likes
has_many :comments


#====================== validation ===========================#

    validates :email_id, confirmation: true , presence: true ,uniqueness: true

validates :password_digest , presence: true  



#===================================Like & Dislike check ======================#

    def already_likes?(post ,like_type)
    
    	 self.likes.where(likeble_id: post.id ,user_id: self.id ,likeble_type: like_type ,like_status: true).count > 0
       
    end
     def already_dislikes?(post ,like_type)
    	
    	 self.likes.where(likeble_id: post.id ,user_id: self.id ,likeble_type: like_type,like_status: false).count > 0
       
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :self_action , only:[:show,:destroy ,:edit ,:update]

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end
  def destroy
    
    session[:user_id] = nil
    @user.destroy
    redirect_to '/'
  end
  def create
    @user = User.create(user_params)
    if @user.save!
      session[:user_id] = @user.id
      redirect_to '/login'
    else
      redirect_to '/signup'
    end
  end
  def update 
      @user.update(user_params)
      redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:f_name,:l_name,:user_name,:dob ,:sex,:dob,:age,:email_id, :password, :password_confirmation)
  end
  def self_action
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  First Name: <%= f.text_field :f_name ,autofocus: true,:required => true  ,title: 'only letter are allowed ,no white space', rel: 'tooltip'%><br>
  Last Name: <%= f.text_field :l_name ,autofocus: true,:required => true  ,title: 'only letter are allowed ,no white space', rel: 'tooltip'%><br>
  Email: <%= f.email_field :email_id ,autofocus: true ,required: true%><br>
  Age: <%= f.number_field :age ,autofocus: true %><br>
  Date of Birth: <%= f.date_field :dob ,required:true %><br>
  Sex: <%= f.select :sex ,["male" ,"female"] ,:selected => "male"%><br>
  Password: <%= f.password_field :password ,required:true%><br>
  Password Confirmation: <%= f.password_field :password_confirmation ,required:true%><br>
  <%= f.submit  %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<%= render 'users/user'%>
 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= render 'users/user'%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
  <pre>First Name: <%= @user.f_name %>
  Last Name: <%= @user.l_name %>
  Email: <%= @user.email_id %>
  Age: <%= @user.age %>
  Date of Birth: <%= @user.dob %>
  Sex: <%= @user.sex %>
  </pre>
  <%= link_to 'Back' , root_path %> | 
  <%= link_to 'Edit' , edit_user_path(@user) %> | 
  <%= link_to 'Delete Your Account' , user_path(@user) ,method: :delete %>