config/routes.rb
Rails.application.routes.draw do

  resources :users 
  resources :posts do
  resource :comments
  end
  root 'posts#index'
        get '/signup' => 'users#new'
        post '/users' => 'users#create'
        get '/login' => 'session#new'
        post '/login' => 'session#create'
        get '/logout' => 'session#destroy'
        get  '/posts/:post_id/comments/:id/edit'=>'comments#edit',as: :edit_post_comment
        patch  '/posts/:post_id/comments/:id/edit'=>'comments#update',as: :update_post_comment
        delete  '/posts/:post_id/comment/:id/delete'=> 'comments#destroy',as: :delete_post_comment
        
        get '/posts/:post_id/comment/:id/like' =>'comments#like',as: :post_comment_like
        get '/posts/:post_id/comment/:id/dislike' =>'comments#dislike',as: :post_comment_dislike

        get '/posts/:post_id/like' =>'posts#like',as: :post_like
        get '/posts/:post_id/dislike' =>'posts#dislike',as: :post_dislike
                  
               

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
	 has_many :likes, as: :likeble
	 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :b_action , only:[ :show ,:update ,:destroy ,:edit ]
  before_action :authorize ,except:[:index ,:show]

  def new
       @post = current_user.posts.new
  end

  def index
  	@posts = Post.all
  end

  def show
  end

  def create


  	   @post = current_user.posts.create(find_params)
  	   if @post.save 
  	   	   redirect_to post_path(@post)
  	   else
  	   		render 'new'
  	   end
  end

  def edit
      
  end
  def destroy
      @post.destroy
   		redirect_to @post
  end

  def update
        @post.update(find_params)
        redirect_to root_path
  end

  def like
      @post = Post.find(params[:post_id])


    if current_user.already_dislikes?(@post ,'Post')
       like = current_user.likes.where(likeble_id: @post.id ,
       user_id: current_user.id ,likeble_type: 'Post' ).first
       like.like_status = true
       like.save
       redirect_to root_path

     else
        if current_user.already_likes?(@post ,'Post')
           redirect_to root_path
        else
           like = @post.likes.create
           like.user_id = current_user.id
           like.like_status = true
           like.save
           redirect_to root_path
        end
    end
  end

  def dislike
      @post = Post.find(params[:post_id])

    if current_user.already_likes?(@post ,'Post')
       like = current_user.likes.where(likeble_id: @post.id ,
       user_id: current_user.id ,likeble_type: 'Post' ).first
       like.like_status = false
       like.save
       redirect_to root_path

     else
        if current_user.already_dislikes?(@post ,'Post')
           redirect_to root_path
        else
           like = @post.likes.create
           like.user_id = current_user.id
           like.like_status = false
           like.save
           redirect_to root_path
        end
    end
  end


  private 
 def b_action
     @post = Post.find(params[:id])
 end
 def find_params
    params.require(:post).permit(:title ,:body)
 end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
         <%= form_for @post do |f| %>
                <pre>
            Title  <%= f.text_field :title %> <br>
            Post   <%= f.text_area :body ,:rows=>'10',:cols=>'50'%>
              <%= f.submit %>
                 </pre>
        <% end %>

<%= link_to  'Home' , root_path %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<%= render 'form'%>
<%= link_to 'Like' ,post_like_path(@post) %>
  &nbsp; &nbsp;<%= @post.likes.count %> <br><br>
<%= link_to 'Back' , post_path(@post) %>

app/views/posts/index.html.erb
<h1>All Post</h1> 
<% if current_user %>
 <h1> Welcome   <%= current_user.f_name %> &nbsp;
  <%= current_user.l_name %></h1> <%= link_to 'Profile' , user_path(current_user)%> | <%= link_to "Logout", logout_path %> |
  <br>
 <%= link_to 'New Post' , new_post_path%>
 <% else %>
  <li><%= link_to 'Login', login_path,class:"active" %> </li><li> <%= link_to 'Signup', signup_path%></li>
  <% end %>

<% @posts.each do |post| %>
<h3><%= post.title %></h3>
<%= truncate(post.body , :length => 325)  %> <br>
<%= link_to 'Show' , post_path(post) %>
<% if current_user %>  
 <%= link_to 'Comment' , new_post_comments_path(post) %>
 
 <%= link_to 'Like' ,post_like_path(post) %>
  &nbsp; &nbsp;<%= post.likes.where(like_status: true).count %>&nbsp; &nbsp;

  <%= link_to 'Unlike' ,post_dislike_path(post) %>
   &nbsp; &nbsp;<%= post.likes.where(like_status: false).count %>
<% if (current_user.id == post.user_id) %>
<%= link_to 'Edit' , edit_post_path(post) %>
<%= link_to  'Delete Post' , post_path(post)  ,:method=> :delete ,:action=> :destroy,:notice=> 'Successfully deleted'%>
<% end %>
<%else%>
<% end %>
<% end %>

 

app/views/posts/new.html.erb
 <h1>Login</h1>
        
  <%=render 'form' %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>
<%= params %>
Title <%= @post.title %> <br>
Post <%= @post.body %>
<br><br>

<%= link_to 'Back' ,root_path%>

<% if current_user %>
<%= link_to 'Like' ,post_like_path(@post) %>

  &nbsp; &nbsp;<%= @post.likes.where(like_status: true).count %>&nbsp; &nbsp;
  <%= link_to 'Unlike' ,post_dislike_path(@post) %>
  
   &nbsp; &nbsp;<%= @post.likes.where(like_status: false).count %> <br><br>
<%= link_to 'Edit' , edit_post_path(@post) %>
<%= link_to  'Delete Post' , post_path(@post)  ,:method=> :delete ,:action=> :destroy,:notice=> 'Successfully deleted'%>
<%else%>
<% end %>